<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_presave()
 */
function crop_image_entity_presave(EntityInterface $entity) {
  \Drupal::service('crop_image.manager')->validateCropImages($entity);
}

/**
 * Implements hook_entity_delete()
 */
function crop_image_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('crop_image.manager')->removeCropImages($entity);
}

/**
 * Implements hook_views_pre_render().
 */
function crop_image_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'image_browser')) {
    $view->element['#attached']['library'][] = 'crop_image/image_browser';
  }
}
