aws_key: AKIA3M7BXYNHGQXRAMZ2
aws_secret: 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
aws_region: us-west-2
_core:
  default_config_hash: ZEmGUDQ8KXtk5Yewte56_Yi7eo711G6rBpFEvKgDnH0
secret_prefix: hobbes
