post_enable_full: 1
post_template: ''
post_template_lock: none
post_allowed_blocks:
  core/paragraph: core/paragraph
  core/image: core/image
  core/heading: core/heading
  core/gallery: core/gallery
  core/list: core/list
  core/quote: core/quote
  core/audio: core/audio
  core/button: core/button
  core/code: core/code
  core/columns: core/columns
  core/column: core/column
  core/cover: core/cover
  core/embed: core/embed
  core/file: core/file
  core/freeform: core/freeform
  core/html: core/html
  core/media-text: core/media-text
  core/preformatted: core/preformatted
  core/pullquote: core/pullquote
  core/separator: core/separator
  core/block: core/block
  core/spacer: core/spacer
  core/subhead: core/subhead
  core/table: core/table
  core/text-columns: core/text-columns
  core/verse: core/verse
  core/video: core/video
  core/all: 0
  core-embed/twitter: core-embed/twitter
  core-embed/youtube: core-embed/youtube
  core-embed/facebook: core-embed/facebook
  core-embed/instagram: core-embed/instagram
  core-embed/soundcloud: core-embed/soundcloud
  core-embed/spotify: core-embed/spotify
  core-embed/flickr: core-embed/flickr
  core-embed/vimeo: core-embed/vimeo
  embed: embed
  core-embed/scribd: core-embed/scribd
  core-embed/slideshare: core-embed/slideshare
  core-embed/ted: core-embed/ted
  core-embed/tumblr: core-embed/tumblr
  core-embed/all: 0
  core-embed/wordpress: 0
  core-embed/amazon-kindle: 0
  core-embed/animoto: 0
  core-embed/cloudup: 0
  core-embed/collegehumor: 0
  core-embed/crowdsignal: 0
  core-embed/dailymotion: 0
  core-embed/hulu: 0
  core-embed/imgur: 0
  core-embed/issuu: 0
  core-embed/kickstarter: 0
  core-embed/meetup-com: 0
  core-embed/mixcloud: 0
  core-embed/polldaddy: 0
  core-embed/reddit: 0
  core-embed/reverbnation: 0
  core-embed/screencast: 0
  core-embed/smugmug: 0
  core-embed/speaker-deck: 0
  core-embed/speaker: 0
  core-embed/videopress: 0
  core-embed/wordpress-tv: 0
post_allowed_drupal_blocks:
  page_title_block: page_title_block
  user_login_block: user_login_block
  'views_block:content_recent-block_1': 'views_block:content_recent-block_1'
  'views_block:who_s_online-who_s_online_block': 'views_block:who_s_online-who_s_online_block'
  'system_menu_block:footer': 'system_menu_block:footer'
  'system_menu_block:main': 'system_menu_block:main'
  'system_menu_block:account': 'system_menu_block:account'
  system_breadcrumb_block: system_breadcrumb_block
  system_messages_block: system_messages_block
  system_branding_block: system_branding_block
  system_powered_by_block: 0
  node_syndicate_block: 0
ckeditor_enable_full: 0
