name: CI Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.3-apache
      env:
        NODE_ENV: production
      ports:
      - 80
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Show files
      run: |
        ls -la
